name: Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hello world 
        run: echo "Hello world"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: good bye world
        run: echo "Good bye world"
        shell: bash
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java JDK 17 
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'adopt'
          java-version: '17'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image:  ramanamuttana/testbuildactionwithgradle
          tags: v1, latest
          registry: docker.io
         # registry: registry-url.io
          dockerfile: Dockerfile.ci
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
